# Generated by Django 3.1.3 on 2020-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_barang', models.CharField(max_length=100)),
                ('harga_barang', models.CharField(max_length=100)),
                ('stock_barang', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
