# Generated by Django 3.1.3 on 2020-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_auto_20201109_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pembelian', models.FloatField()),
                ('tanggal_penjualan', models.DateTimeField(auto_now_add=True)),
                ('keterangan_penjualan', models.TextField()),
            ],
        ),
    ]
