# Generated by Django 3.1.3 on 2020-11-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0003_penjualan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('barang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.barang')),
                ('penjualan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.penjualan')),
            ],
        ),
    ]
